import { Package } from './schema';

// Define the package data with explicit typing and required fields
export const packageData: Array<Omit<Package, 'rating' | 'reviews' | 'location' | 'image'> & {
  rating?: number | null;
  reviews?: number | null;
  location?: string | null;
  image?: string | null;
}> = [
  // Domestic Packages
  {
    id: 1,
    title: "Himachal Adventure Package",
    description: "Experience the beauty of Himachal Pradesh with visits to Manali, Shimla, and the stunning Spiti Valley.",
    destination: "Himachal Pradesh",
    price: 25000,
    duration: 6,
    category: "domestic",
    subCategory: "mountain",
    imageUrl: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    highlights: ["Rohtang Pass visit", "Solang Valley activities", "Old Manali exploration", "Spiti Valley tour"],
    itinerary: ["Day 1-2: Shimla sightseeing and Mall Road", "Day 3-4: Manali and Solang Valley", "Day 5-6: Spiti Valley tour"]
  },
  {
    id: 2,
    title: "Uttrakhand Divine Journey",
    description: "Explore the spiritual and natural wonders of Uttrakhand, including Rishikesh, Haridwar, and Mussoorie.",
    destination: "Uttrakhand",
    price: 22000,
    duration: 7,
    category: "domestic",
    subCategory: "spiritual",
    imageUrl: "https://images.unsplash.com/photo-1602416589293-96cd58545efe?w=800&q=80",
    highlights: ["Ganges Aarti", "River rafting", "Valley of flowers", "Yoga sessions"],
    itinerary: ["Day 1-2: Rishikesh yoga and rafting", "Day 3-4: Haridwar temples", "Day 5-7: Mussoorie hill station"]
  },
  {
    id: 3,
    title: "Andaman Island Paradise",
    description: "Discover the pristine beaches and crystal-clear waters of the Andaman Islands.",
    destination: "Andaman Islands",
    price: 45000,
    duration: 6,
    category: "domestic",
    subCategory: "beach",
    imageUrl: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&q=80",
    highlights: ["Radhanagar Beach", "Scuba diving", "Cellular Jail visit", "Island hopping"],
    itinerary: ["Day 1-2: Port Blair and Cellular Jail", "Day 3-4: Havelock Island", "Day 5-6: Neil Island"]
  },
  {
    id: 4,
    title: "Royal Rajasthan Tour",
    description: "Experience the royal heritage and desert culture of Rajasthan.",
    destination: "Rajasthan",
    price: 35000,
    duration: 8,
    category: "domestic",
    subCategory: "heritage",
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80",
    highlights: ["Palace tours", "Desert safari", "Folk music", "Heritage hotels"],
    itinerary: ["Day 1-2: Jaipur Pink City", "Day 3-4: Udaipur lakes", "Day 5-6: Jodhpur fort", "Day 7-8: Jaisalmer desert"]
  },
  {
    id: 5,
    title: "Golden Triangle Classic",
    description: "Explore India's famous Golden Triangle: Delhi, Agra, and Jaipur.",
    destination: "Delhi-Agra-Jaipur",
    price: 28000,
    duration: 6,
    category: "domestic",
    subCategory: "heritage",
    imageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80",
    highlights: ["Taj Mahal", "Red Fort", "Amber Palace", "Local markets"],
    itinerary: ["Day 1-2: Delhi exploration", "Day 3-4: Agra and Taj Mahal", "Day 5-6: Jaipur sightseeing"]
  },
  {
    id: 6,
    title: "Ladakh Adventure Trek",
    description: "Experience the breathtaking landscapes and Buddhist culture of Ladakh.",
    destination: "Ladakh",
    price: 40000,
    duration: 8,
    category: "domestic",
    subCategory: "adventure",
    imageUrl: "https://images.unsplash.com/photo-1514604426857-f54c81c8daef?w=800&q=80",
    highlights: ["Pangong Lake", "Monasteries", "Khardung La", "Nubra Valley"],
    itinerary: ["Day 1-2: Leh acclimatization", "Day 3-4: Monastery tour", "Day 5-6: Pangong Lake", "Day 7-8: Nubra Valley"]
  },
  {
    id: 7,
    title: "Sikkim-Darjeeling Expedition",
    description: "Discover the tea gardens and Himalayan views of Sikkim and Darjeeling.",
    destination: "Sikkim-Darjeeling",
    price: 32000,
    duration: 7,
    category: "domestic",
    subCategory: "nature",
    imageUrl: "https://images.unsplash.com/photo-1544634076-92642164717d?w=800&q=80",
    highlights: ["Tea gardens", "Tiger Hill sunrise", "Monastery visits", "Cable car ride"],
    itinerary: ["Day 1-3: Darjeeling exploration", "Day 4-5: Pelling", "Day 6-7: Gangtok"]
  },
  {
    id: 8,
    title: "Meghalaya Nature Tour",
    description: "Explore the living root bridges and waterfalls of Meghalaya.",
    destination: "Meghalaya",
    price: 28000,
    duration: 6,
    category: "domestic",
    subCategory: "nature",
    imageUrl: "https://images.unsplash.com/photo-1627894006066-b45ef482e6b7?w=800&q=80",
    highlights: ["Living root bridges", "Cherrapunji", "Dawki River", "Caves"],
    itinerary: ["Day 1-2: Shillong", "Day 3-4: Cherrapunji", "Day 5-6: Dawki and Mawlynnong"]
  },
  {
    id: 9,
    title: "Kashmir Paradise Package",
    description: "Experience the paradise on earth with Kashmir's scenic beauty.",
    destination: "Kashmir",
    price: 35000,
    duration: 7,
    category: "domestic",
    subCategory: "nature",
    imageUrl: "https://images.unsplash.com/photo-1566837497706-4570abb17b8e?w=800&q=80",
    highlights: ["Dal Lake", "Gulmarg", "Pahalgam", "Mughal gardens"],
    itinerary: ["Day 1-3: Srinagar and Dal Lake", "Day 4-5: Gulmarg", "Day 6-7: Pahalgam"]
  },
  {
    id: 10,
    title: "Arunachal Explorer",
    description: "Discover the untouched beauty of Arunachal Pradesh.",
    destination: "Arunachal Pradesh",
    price: 38000,
    duration: 8,
    category: "domestic",
    subCategory: "adventure",
    imageUrl: "https://images.unsplash.com/photo-1623492701902-47dc207df5cf?w=800&q=80",
    highlights: ["Tawang Monastery", "Tribal villages", "Sela Pass", "Wildlife"],
    itinerary: ["Day 1-2: Bomdila", "Day 3-4: Tawang", "Day 5-6: Dirang", "Day 7-8: Ziro Valley"]
  },
  {
    id: 11,
    title: "Goa Beach Holiday",
    description: "Enjoy the beaches, nightlife, and Portuguese heritage of Goa.",
    destination: "Goa",
    price: 20000,
    duration: 5,
    category: "domestic",
    subCategory: "beach",
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    highlights: ["Beach hopping", "Water sports", "Old Goa churches", "Nightlife"],
    itinerary: ["Day 1-2: North Goa beaches", "Day 3: Old Goa tour", "Day 4-5: South Goa relaxation"]
  },
  {
    id: 12,
    title: "Kerala Backwaters",
    description: "Experience the serene backwaters and culture of Kerala.",
    destination: "Kerala",
    price: 30000,
    duration: 6,
    category: "domestic",
    subCategory: "nature",
    imageUrl: "https://images.unsplash.com/photo-1602416589293-96cd58545efe?w=800&q=80",
    highlights: ["Houseboat stay", "Ayurveda", "Tea plantations", "Beaches"],
    itinerary: ["Day 1-2: Kochi", "Day 3-4: Alleppey backwaters", "Day 5-6: Munnar"]
  },
  {
    id: 13,
    title: "Karnataka Heritage",
    description: "Explore the historic sites and natural beauty of Karnataka.",
    destination: "Karnataka",
    price: 25000,
    duration: 7,
    category: "domestic",
    subCategory: "heritage",
    imageUrl: "https://images.unsplash.com/photo-1600100789887-2215714615e4?w=800&q=80",
    highlights: ["Hampi ruins", "Mysore Palace", "Coorg hills", "Wildlife"],
    itinerary: ["Day 1-2: Bangalore", "Day 3-4: Mysore", "Day 5-7: Coorg"]
  },
  {
    id: 14,
    title: "Tamil Nadu Temple Tour",
    description: "Visit the ancient temples and cultural sites of Tamil Nadu.",
    destination: "Tamil Nadu",
    price: 28000,
    duration: 6,
    category: "domestic",
    subCategory: "spiritual",
    imageUrl: "https://images.unsplash.com/photo-1582510803125-8cc9c56ac4d6?w=800&q=80",
    highlights: ["Meenakshi Temple", "Shore Temple", "Hill stations", "Classical dance"],
    itinerary: ["Day 1-2: Chennai", "Day 3-4: Madurai", "Day 5-6: Mahabalipuram"]
  },
  // International Packages
  {
    id: 15,
    title: "Bali Paradise",
    description: "Experience the tropical paradise and cultural richness of Bali.",
    destination: "Bali",
    price: 75000,
    duration: 6,
    category: "international",
    subCategory: "beach",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    highlights: ["Ubud forests", "Temple visits", "Beach clubs", "Rice terraces"],
    itinerary: ["Day 1-2: Seminyak beaches", "Day 3-4: Ubud culture", "Day 5-6: Nusa Dua luxury"]
  },
  {
    id: 16,
    title: "Dubai Extravaganza",
    description: "Discover the modern marvels and desert beauty of Dubai.",
    destination: "Dubai",
    price: 85000,
    duration: 5,
    category: "international",
    subCategory: "luxury",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    highlights: ["Burj Khalifa", "Desert safari", "Gold Souk", "Palm Jumeirah"],
    itinerary: ["Day 1-2: Dubai city tour", "Day 3: Desert adventure", "Day 4-5: Abu Dhabi"]
  },
  {
    id: 17,
    title: "Singapore Highlights",
    description: "Explore the modern city-state of Singapore.",
    destination: "Singapore",
    price: 70000,
    duration: 5,
    category: "international",
    subCategory: "city",
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    highlights: ["Gardens by the Bay", "Universal Studios", "Marina Bay Sands", "Sentosa"],
    itinerary: ["Day 1-2: City exploration", "Day 3: Sentosa Island", "Day 4-5: Shopping and leisure"]
  },
  {
    id: 18,
    title: "Vietnam Discovery",
    description: "Experience the natural wonders and rich history of Vietnam.",
    destination: "Vietnam",
    price: 65000,
    duration: 7,
    category: "international",
    subCategory: "culture",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80",
    highlights: ["Ha Long Bay", "Cu Chi Tunnels", "Hoi An", "Mekong Delta"],
    itinerary: ["Day 1-2: Hanoi", "Day 3-4: Ha Long Bay", "Day 5-7: Ho Chi Minh City"]
  },
  {
    id: 19,
    title: "Thailand Adventure",
    description: "Discover the beaches, temples, and cuisine of Thailand.",
    destination: "Thailand",
    price: 60000,
    duration: 7,
    category: "international",
    subCategory: "beach",
    imageUrl: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
    highlights: ["Bangkok temples", "Phi Phi Islands", "Night markets", "Thai massage"],
    itinerary: ["Day 1-2: Bangkok", "Day 3-4: Chiang Mai", "Day 5-7: Phuket"]
  },
  {
    id: 20,
    title: "Maldives Paradise",
    description: "Relax in luxury overwater villas in the Maldives.",
    destination: "Maldives",
    price: 120000,
    duration: 5,
    category: "international",
    subCategory: "luxury",
    imageUrl: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    highlights: ["Overwater villa", "Snorkeling", "Spa treatments", "Water sports"],
    itinerary: ["Day 1-5: Resort activities and water sports"]
  },
  {
    id: 21,
    title: "Malaysia Explorer",
    description: "Experience the diverse attractions of Malaysia.",
    destination: "Malaysia",
    price: 55000,
    duration: 6,
    category: "international",
    subCategory: "city",
    imageUrl: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    highlights: ["Petronas Towers", "Batu Caves", "Langkawi", "Food tour"],
    itinerary: ["Day 1-2: Kuala Lumpur", "Day 3-4: Penang", "Day 5-6: Langkawi"]
  },
  {
    id: 22,
    title: "Sri Lanka Heritage",
    description: "Discover the cultural and natural wonders of Sri Lanka.",
    destination: "Sri Lanka",
    price: 45000,
    duration: 7,
    category: "international",
    subCategory: "culture",
    imageUrl: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=800&q=80",
    highlights: ["Sigiriya Rock", "Tea plantations", "Temple of Tooth", "Wildlife safari"],
    itinerary: ["Day 1-2: Colombo", "Day 3-4: Kandy", "Day 5-7: Nuwara Eliya"]
  }
];
